sudo: required
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
    - ncftp
os:
- linux
language: node_js
node_js:
- '8'
before_install:
- npm set progress false
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run lint.all
- npm run test.all
- npm run build.cfb.prod
# - npm run doc.all
# - sh deploy-docs.sh
after_success:
- npm run codecov
env:
  global:
  - secure: UJ0/fz6H4N3ot3YkSUVjB5pEYX6wtYhHyclxlWPrJdkFrvFVtiv50NdmCVXNXR1ig2mZ7uDwcudAo6mUNGSygBxWpnMIAKdJ6g7eALNgPrNOe722utVpG6R8q19G4EDbqHnUUXDMvxBbXY3cgEH8sMppcUP0VwSTGBRnrc7nv4SYMNywJwfklHTI0Iioj7XQfDSBG6PdP8nCKU4O/mtM53zfv+ruJmyrQR2iIQy6Cs+7/AsDmQGGyIJXaQoAX6t4L7kBVEzPE7RdupxpkVbhcZZl8t1tCf/gR3gAWNMaHzTJvrSNrVRYXOdbgsHqUJLScw8gZS+DpJjn9G682rZ+3jxw0HMi/cAxEn+/o3zNCoRxKOMeEWPO2RE5ej11wepocFlxru17Sn9bJtUELsOOZ+z6I/RDGX7hgtTDsNPslQ/sA9K4vv7s0C5ONGFPny2nf+bBsd0DGVFtSbSO9cKKD6Qpkj3P8Xl+jn68nGEWUB4J/Go8wQLG3ULPV576sfCaiBb3UwyuOBpjFDdE14HZbQIKmmWnVtEm6EnX0eRNMONNs8Rtc9dihAM/CqhJKcWyyqY9IBPqk0F+Hl+7ryB/ZWWsvrevTmLYn/G3IgNUwY/zr/mYt3Ydu6UgHmLHcap5I4gKDGl1i5qcDcpjoP/7mwgZg9/dfuPFyvEjOmHxYjw=
  - secure: vMmWq5ZmfqjYtFHF4cWjtw7RnZwnO5SFAFRc7hyhFc0SUKorvqkZ/Xn0mKFojYX8mNXFQjqnfdXgpPmif7W34uL40B2uhbqdKRSgOAjy5i9RxEjnMbaU6jRtGH1fmVD7MnxBFGLo3DpurKOz69XjGUbULaVR5qkQOFlu2ZFRvNkPbcHqbWlCkAeK0bO8y8NlxkSTVSw8ryzgJIEfRA0uEj9AvRz/bWZ334PO8C1nyUvDLHwbmndQs/B/gyOiyUGB9XVCPiy10OqKjtYEYyK1oSxJFY7qQrhQMltUml1ptgaviGWgaaMWKCqYqtt69nIhZcnoHucaFjXqMeWREpvW4lQnvP1EaGDrHBX6ns/HTIvZncxyTAd2myN7R1SC6aZm2Mdp7ataTa18/z2zSLDxTwnZXfC0H2jlupgTRz7dATIyIhRigf4bNwPs6PV63AT6xSIIlleQt9BJ2Rov8yj++0LKfZ0DVMouZu7RauCeDn01bdBsAjpz32E8aizQJcE9P3660xouHWqGMvKexacG1OaWVTUpuKdui/a2bL1ByV3IoFplvlxJ+deA0dRRQq+Tx+PJy0Y6BD5iErvgt4WFiIGRhxzQkKPHPG/tyyBLapNG3fdRTqeBiCnOGS0TEcPfC0xLMPTi7NN7zsC1q3WElsHQDfLBFAckbkOkZ893pPM=
  - secure: 1lVXVH/zRWNw8rqu39nV7VQ80hADsXM0QkUtZY4k7nXnZrqBx8JoVH7ANHiZk9mOqoskWIzbS6SFmjUgDyB8phUJ1WCg1Mhx9XU7sBh8RwLEPmZylbgfGid8qU0RkW06PS+F5GHQk4J6rhpDxY36jDoy5MLjWwQ9HKkgL2YLoH29PiBGPwpDtV7wWJSNPhKic18Ft6oHQhDNcW/pbFpFpJNDvmI3LrhT6SmWSPLXBJ0rovaDiy163nzECSbHRBWG3mkWXa3IJoID+5NPp4DQrIFjkmPXN3gyIC3rYgzQB5nmTFTNEZpg7l1am6ra803TSavnlvUFY3DMuSDgzogqVBGas/srQ/1Kts943DLVJJNutAczkZ2w0QDc6S35j3OZ2Yds9NrYpVzHa/miUGBfkbPkrBhwDF8kBIc2aD0mobf/lXrApYtzEkm0KJaVInPuCxfkMLeSjfzkKcxhs7AOSq87lYMd6m3O9OGwU6aHB+aaAJlXkrJ04X9UDd1Sv9mDTCo1EkqmgvGAvQ/5wxdwX6BnzCJIiNgcGtAJxhEPOZKMXqgZrG6WFat/qiofrqslEuKlQRnQAYn9qDWwenvN4KHqP2ardAGR8/j52MTm5HVIGNNPAmZh144jF7sy8pcPpUnFXM0ZZQ8ltZv37gGvmnkC4Y0pmuoyJJc+pHkVZ5M=
